name: todo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  charts_flutter: ^0.12.0
  email_validator: ^2.0.1
  cloud_firestore: ^3.1.16
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  pie_chart: ^5.3.1
  sliver_bar_chart: ^0.0.1
  image_picker: ^0.8.5+3
  file: ^6.1.2
  firebase_storage: ^10.2.17
  syncfusion_flutter_charts: ^20.1.59
  http: ^0.13.4
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
